# Generated by Django 4.1.5 on 2023-02-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interpreters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "payment",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Payment Method"
                    ),
                ),
                (
                    "center",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Service Center"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total Amount",
                    ),
                ),
            ],
        ),
    ]
