# Generated by Django 4.1.5 on 2023-02-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_rename_interpreters_interpreter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("call_id", models.BigIntegerField(verbose_name="Call Id")),
                ("call_date", models.DateTimeField(verbose_name="Call Time")),
                ("duration", models.IntegerField(verbose_name="Interpreter Call Time")),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Language"
                    ),
                ),
                (
                    "pay",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Interpreter Pay"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Interpreter Name"
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Customer Name"
                    ),
                ),
            ],
        ),
    ]
