# Generated by Django 4.1.5 on 2023-02-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_calllog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="call_id",
            field=models.DecimalField(
                decimal_places=8, max_digits=24, verbose_name="Call Id"
            ),
        ),
    ]
