# Generated by Django 4.1.5 on 2023-02-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0004_alter_calllog_call_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="call_date",
            field=models.DateTimeField(null=True, verbose_name="Call Time"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="call_id",
            field=models.DecimalField(
                decimal_places=8, max_digits=24, null=True, verbose_name="Call Id"
            ),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="duration",
            field=models.IntegerField(null=True, verbose_name="Interpreter Call Time"),
        ),
    ]
