# Generated by Django 4.1.5 on 2023-02-06 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_alter_calllog_call_date_alter_calllog_call_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="pay",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Interpreter Pay",
            ),
        ),
    ]
