# Generated by Django 4.1.5 on 2023-02-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_alter_calllog_pay"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calllog",
            old_name="call_id",
            new_name="CallId",
        ),
        migrations.RenameField(
            model_name="calllog",
            old_name="call_date",
            new_name="Call_Time",
        ),
        migrations.RenameField(
            model_name="calllog",
            old_name="customer",
            new_name="Customer_Name",
        ),
        migrations.RenameField(
            model_name="calllog",
            old_name="name",
            new_name="Interpreter_Name",
        ),
        migrations.RenameField(
            model_name="calllog",
            old_name="pay",
            new_name="Interpreter_Pay",
        ),
        migrations.RenameField(
            model_name="calllog",
            old_name="language",
            new_name="Language",
        ),
        migrations.RemoveField(
            model_name="calllog",
            name="duration",
        ),
        migrations.AddField(
            model_name="calllog",
            name="Interpreter_Calltime",
            field=models.IntegerField(null=True, verbose_name="Interpreter Calltime"),
        ),
    ]
