# Generated by Django 4.1.5 on 2023-02-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_rename_call_id_calllog_callid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="CallId",
            field=models.CharField(blank=True, max_length=25, verbose_name="Call Id"),
        ),
    ]
