# Generated by Django 4.1.5 on 2023-02-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0011_alter_calllog_interpreter_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Pay",
            field=models.FloatField(verbose_name="Interpreter Pay"),
        ),
    ]
