# Generated by Django 4.1.5 on 2023-02-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0013_alter_calllog_interpreter_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Calltime",
            field=models.CharField(max_length=20, verbose_name="Interpreter Calltime"),
        ),
    ]
