# Generated by Django 4.1.5 on 2023-02-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0014_alter_calllog_interpreter_calltime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Calltime",
            field=models.IntegerField(null=True, verbose_name="Interpreter Calltime"),
        ),
    ]
