# Generated by Django 4.1.5 on 2023-02-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0015_alter_calllog_interpreter_calltime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Calltime",
            field=models.CharField(max_length=20, verbose_name="Interpreter Calltime"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Pay",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Interpreter Pay",
            ),
        ),
    ]
