# Generated by Django 4.1.5 on 2023-02-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0016_alter_calllog_interpreter_calltime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Call_Time",
            field=models.DateTimeField(null=True, verbose_name="Call Time"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Calltime",
            field=models.IntegerField(null=True, verbose_name="Interpreter Calltime"),
        ),
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Pay",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Interpreter Pay",
            ),
        ),
    ]
