# Generated by Django 4.1.5 on 2023-02-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0018_alter_calllog_interpreter_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Pay",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Interpreter Pay",
            ),
        ),
    ]
