# Generated by Django 4.1.5 on 2023-02-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0019_alter_calllog_interpreter_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interpreter",
            name="amount",
            field=models.FloatField(null=True, verbose_name="Total Amount"),
        ),
    ]
