# Generated by Django 4.1.5 on 2023-02-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0020_alter_interpreter_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calllog",
            name="Interpreter_Pay",
            field=models.FloatField(null=True, verbose_name="Interpreter Pay"),
        ),
    ]
